WorkspaceName=rss
WorkspaceDescription=child of Sim7
StartOfWaterYear=01Jan
MinComputePasses=2
StorCalcErrTolFac=1.0E-5
StorCalcSubSteps=200
ConsiderROC=true
UseLookAhead=true
IterateNonConstantROC=true
MinLookAheadDays=3.0
MaxLookAheadDays=14.0
MaxIterNonConstROC=20
FlowTol=1.0E-6
StorTol=1.0E-6
InducedSurchargeMaxIter=50
SaveReleaseToGuideCurve=false
NoSysHydroRoutingSteps=false
Extents=-1000.0,1000.0,-1000.0,1000.0

ManagerProxyBegin
Name=Temp7-----0
Description=
Path=rss/Temp7-----.simrun
Class=hec.rss.model.RssSimRun
Index=0
ModifiedTime=1647365334038
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:Temp7
Description=
Path=rss/Temp7-----0_Temp7.malt
Class=hec.model.ModelAlt
Index=1
ModifiedTime=1647365333326
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:AMR_Net_5
Description=TCD-Setup improved
Path=rss/networks/Temp7-----0_AMR_Net_5/Temp7-----0_AMR_Net_5.rsys
Class=hec.rss.model.RssSystem
Index=2
ModifiedTime=1651526656749
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:Temp7
Description=(TS Data Set)
Path=rss/Temp7-----0_Temp7.fits
Class=hec.model.TSDataSet
Index=3
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:Temp7Obs
Description=(Observed TS Data Set)
Path=rss/Temp7-----0_Temp7Obs.fits
Class=hec.model.TSDataSet
Index=4
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:Temp7
Description=(Global Variable Data Set)
Path=rss/Temp7-----0_Temp7.igv
Class=hec.rss.model.GVDataSet
Index=5
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:Temp7
Description=
Path=rss/Temp7-----0_Temp7.ralt
Class=hec.rss.model.RssAlt
Index=6
ModifiedTime=1651526762474
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:G7
Description=
Path=rss/wq/geometry/Temp7-----0_G7.geometry
Class=hec.rss.wq.model.WqGeometry
Index=7
ModifiedTime=1647365333831
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:XS_01
Description=Cross Sections for RAS Cross Section file XS_01.shp
Path=rss/wq/geometry/Temp7-----0_XS_01.crossSections
Class=hec.rss.wq.model.CrossSectionManager
Index=8
ModifiedTime=1647365333764
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:AMR_Mather
Description=
Path=rss/wq/Temp7-----0_AMR_Mather.met
Class=hec.rss.wq.model.MetData
Index=9
ModifiedTime=1650481456636
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:AMR_Water_Temperature
Description=
Path=rss/wq//Temp7-----0_AMR_Water_Temperature.constituentSet
Class=hec.rss.wq.model.ConstituentSetManager
Index=10
ModifiedTime=1647365333872
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:BCS7
Description=
Path=rss/wq//Temp7-----0_BCS7.boundaryCondSet
Class=hec.rss.wq.model.BoundaryConditionSetManager
Index=11
ModifiedTime=1647365333902
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:ICS7
Description=
Path=rss/wq//Temp7-----0_ICS7.initialCondSet
Class=hec.rss.wq.model.InitialConditionSetManager
Index=12
ModifiedTime=1647365333936
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:DCS7
Description=
Path=rss/wq//Temp7-----0_DCS7.dispersionCoeff
Class=hec.rss.wq.model.dispersionCoeff.DispersionSetManager
Index=13
ModifiedTime=1647365333981
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0:PS7
Description=
Path=rss/wq//Temp7-----0_PS7.wqParameters
Class=hec.rss.wq.model.wqParameters.ParameterSetManager
Index=14
ModifiedTime=1647365334024
ManagerProxyEnd

ManagerProxyBegin
Name=Temp7-----0
Description=ResSim Run for Temp7-----0
Path=rss/Temp7-----0.rssrun
Class=hec.rss.model.RssRun
Index=16
ModifiedTime=9223372036854775807
ManagerProxyEnd
AllowStateVarsAsJavaClasses=false
AllowScriptedRulesAsJavaClasses=false
HasWaterQualityModule=false
