WorkspaceName=rss
WorkspaceDescription=child of Net6_FO3
StartOfWaterYear=01Jan
MinComputePasses=2
StorCalcErrTolFac=1.0E-5
StorCalcSubSteps=200
ConsiderROC=true
UseLookAhead=true
IterateNonConstantROC=true
MinLookAheadDays=3.0
MaxLookAheadDays=14.0
MaxIterNonConstROC=20
FlowTol=1.0E-6
StorTol=1.0E-6
InducedSurchargeMaxIter=50
SaveReleaseToGuideCurve=false
NoSysHydroRoutingSteps=false
Extents=-1000.0,1000.0,-1000.0,1000.0

ManagerProxyBegin
Name=Temp8-----0
Description=
Path=rss/Temp8-----.simrun
Class=hec.rss.model.RssSimRun
Index=0
ModifiedTime=1654549496267
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=
Path=rss/Temp8-----0_Temp8.malt
Class=hec.model.ModelAlt
Index=1
ModifiedTime=1654549495608
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:AMR_Net_6
Description=Added Mormon Ravine
Path=rss/networks/Temp8-----0_AMR_Net_6/Temp8-----0_AMR_Net_6.rsys
Class=hec.rss.model.RssSystem
Index=2
ModifiedTime=1654549518511
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=Adds Mormon Ravine Flow (TS Data Set)
Path=rss/Temp8-----0_Temp8.fits
Class=hec.model.TSDataSet
Index=3
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8Obs
Description=Adds Mormon Ravine Flow (Observed TS Data Set)
Path=rss/Temp8-----0_Temp8Obs.fits
Class=hec.model.TSDataSet
Index=4
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=Adds Mormon Ravine Flow (Global Variable Data Set)
Path=rss/Temp8-----0_Temp8.igv
Class=hec.rss.model.GVDataSet
Index=5
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=Adds Mormon Ravine Flow
Path=rss/Temp8-----0_Temp8.ralt
Class=hec.rss.model.RssAlt
Index=6
ModifiedTime=1654549496264
ManagerProxyEnd

ManagerProxyBegin
Name=Untitled
Description=
Path=rss/Temp8-----0.rssrun
Class=hec.rss.model.RssRun
Index=8
ModifiedTime=9223372036854775807
ManagerProxyEnd
AllowStateVarsAsJavaClasses=false
AllowScriptedRulesAsJavaClasses=false
HasWaterQualityModule=false
