WorkspaceName=rss
WorkspaceDescription=child of 2017.12.31-2400
StartOfWaterYear=01Jan
MinComputePasses=2
StorCalcErrTolFac=1.0E-5
StorCalcSubSteps=200
ConsiderROC=true
UseLookAhead=true
IterateNonConstantROC=true
MinLookAheadDays=3.0
MaxLookAheadDays=14.0
MaxIterNonConstROC=20
FlowTol=1.0E-6
StorTol=1.0E-6
InducedSurchargeMaxIter=50
SaveReleaseToGuideCurve=false
NoSysHydroRoutingSteps=false
Extents=-1000.0,1000.0,-1000.0,1000.0

ManagerProxyBegin
Name=Temp6a----0
Description=
Path=rss/Temp6a----.simrun
Class=hec.rss.model.RssSimRun
Index=0
ModifiedTime=1647026449150
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:Temp6a
Description=
Path=rss/Temp6a----0_Temp6a.malt
Class=hec.model.ModelAlt
Index=1
ModifiedTime=1647026448355
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:AMR_Net_5
Description=TCD-Setup improved
Path=rss/networks/Temp6a----0_AMR_Net_5/Temp6a----0_AMR_Net_5.rsys
Class=hec.rss.model.RssSystem
Index=2
ModifiedTime=1647356636609
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:Temp6a
Description=(TS Data Set)
Path=rss/Temp6a----0_Temp6a.fits
Class=hec.model.TSDataSet
Index=3
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:Temp6aObs
Description=(Observed TS Data Set)
Path=rss/Temp6a----0_Temp6aObs.fits
Class=hec.model.TSDataSet
Index=4
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:Temp6a
Description=(Global Variable Data Set)
Path=rss/Temp6a----0_Temp6a.igv
Class=hec.rss.model.GVDataSet
Index=5
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:Temp6a
Description=Test
Path=rss/Temp6a----0_Temp6a.ralt
Class=hec.rss.model.RssAlt
Index=6
ModifiedTime=1647289685668
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:G6
Description=
Path=rss/wq/geometry/Temp6a----0_G6.geometry
Class=hec.rss.wq.model.WqGeometry
Index=7
ModifiedTime=1647026448910
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:XS_01
Description=Cross Sections for RAS Cross Section file XS_01.shp
Path=rss/wq/geometry/Temp6a----0_XS_01.crossSections
Class=hec.rss.wq.model.CrossSectionManager
Index=8
ModifiedTime=1647026448826
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:AMR_Mather
Description=
Path=rss/wq/Temp6a----0_AMR_Mather.met
Class=hec.rss.wq.model.MetData
Index=9
ModifiedTime=1647026448899
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:AMR_Water_Temperature
Description=
Path=rss/wq//Temp6a----0_AMR_Water_Temperature.constituentSet
Class=hec.rss.wq.model.ConstituentSetManager
Index=10
ModifiedTime=1647026448962
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:BCS6
Description=
Path=rss/wq//Temp6a----0_BCS6.boundaryCondSet
Class=hec.rss.wq.model.BoundaryConditionSetManager
Index=11
ModifiedTime=1647026448997
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:ICS6
Description=
Path=rss/wq//Temp6a----0_ICS6.initialCondSet
Class=hec.rss.wq.model.InitialConditionSetManager
Index=12
ModifiedTime=1647026449034
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:DCS6
Description=
Path=rss/wq//Temp6a----0_DCS6.dispersionCoeff
Class=hec.rss.wq.model.dispersionCoeff.DispersionSetManager
Index=13
ModifiedTime=1647026449081
ManagerProxyEnd

ManagerProxyBegin
Name=Temp6a----0:PS6
Description=
Path=rss/wq//Temp6a----0_PS6.wqParameters
Class=hec.rss.wq.model.wqParameters.ParameterSetManager
Index=14
ModifiedTime=1647026449132
ManagerProxyEnd

ManagerProxyBegin
Name=Untitled
Description=
Path=rss/Temp6a----0.rssrun
Class=hec.rss.model.RssRun
Index=16
ModifiedTime=9223372036854775807
ManagerProxyEnd
AllowStateVarsAsJavaClasses=false
AllowScriptedRulesAsJavaClasses=false
HasWaterQualityModule=false
