WorkspaceName=rss
WorkspaceDescription=child of Net6_WQ1
StartOfWaterYear=01Jan
MinComputePasses=2
StorCalcErrTolFac=1.0E-5
StorCalcSubSteps=200
ConsiderROC=true
UseLookAhead=true
IterateNonConstantROC=true
MinLookAheadDays=3.0
MaxLookAheadDays=14.0
MaxIterNonConstROC=20
FlowTol=1.0E-6
StorTol=1.0E-6
InducedSurchargeMaxIter=50
SaveReleaseToGuideCurve=false
NoSysHydroRoutingSteps=false
InvalidGlobalVariableIsErrorfalse
Extents=-1000.0,1000.0,-1000.0,1000.0

ManagerProxyBegin
Name=Temp8-----0
Description=
Path=rss/Temp8-----.simrun
Class=hec.rss.model.RssSimRun
Index=0
ModifiedTime=1654552141785
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=
Path=rss/Temp8-----0_Temp8.malt
Class=hec.model.ModelAlt
Index=1
ModifiedTime=1654552140839
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:AMR_Net_6
Description=Added Mormon Ravine
Path=rss/networks/Temp8-----0_AMR_Net_6/Temp8-----0_AMR_Net_6.rsys
Class=hec.rss.model.RssSystem
Index=2
ModifiedTime=1654633631591
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=Adds Mormon Ravine Flow (TS Data Set)
Path=rss/Temp8-----0_Temp8.fits
Class=hec.model.TSDataSet
Index=3
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8Obs
Description=Adds Mormon Ravine Flow (Observed TS Data Set)
Path=rss/Temp8-----0_Temp8Obs.fits
Class=hec.model.TSDataSet
Index=4
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=Adds Mormon Ravine Flow (Global Variable Data Set)
Path=rss/Temp8-----0_Temp8.igv
Class=hec.rss.model.GVDataSet
Index=5
ModifiedTime=9223372036854775807
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Temp8
Description=Adds Mormon Ravine Flow
Path=rss/Temp8-----0_Temp8.ralt
Class=hec.rss.model.RssAlt
Index=6
ModifiedTime=1654626137579
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Net6_G1
Description=
Path=rss/wq/geometry/Temp8-----0_Net6_G1.geometry
Class=hec.rss.wq.model.WqGeometry
Index=7
ModifiedTime=1654552141563
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:XS_01
Description=Cross Sections for RAS Cross Section file XS_01.shp
Path=rss/wq/geometry/Temp8-----0_XS_01.crossSections
Class=hec.rss.wq.model.CrossSectionManager
Index=8
ModifiedTime=1654552141501
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:Fair Oaks and FP Combined
Description=
Path=rss/wq/Temp8-----0_Fair_Oaks_and_FP_Combined.met
Class=hec.rss.wq.model.MetData
Index=9
ModifiedTime=1654552141557
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:AMR_Water_Temperature
Description=
Path=rss/wq//Temp8-----0_AMR_Water_Temperature.constituentSet
Class=hec.rss.wq.model.ConstituentSetManager
Index=10
ModifiedTime=1654552141602
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:BCS_Net6
Description=
Path=rss/wq//Temp8-----0_BCS_Net6.boundaryCondSet
Class=hec.rss.wq.model.BoundaryConditionSetManager
Index=11
ModifiedTime=1654626164610
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:ICS_Net6
Description=
Path=rss/wq//Temp8-----0_ICS_Net6.initialCondSet
Class=hec.rss.wq.model.InitialConditionSetManager
Index=12
ModifiedTime=1654552141669
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:DCS_Net6
Description=
Path=rss/wq//Temp8-----0_DCS_Net6.dispersionCoeff
Class=hec.rss.wq.model.dispersionCoeff.DispersionSetManager
Index=13
ModifiedTime=1654633779072
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0:GeoNet6_PS
Description=
Path=rss/wq//Temp8-----0_GeoNet6_PS.wqParameters
Class=hec.rss.wq.model.wqParameters.ParameterSetManager
Index=14
ModifiedTime=1654633821259
ManagerProxyEnd

ManagerProxyBegin
Name=Temp8-----0
Description=ResSim Run for Temp8-----0
Path=rss/Temp8-----0.rssrun
Class=hec.rss.model.RssRun
Index=16
ModifiedTime=9223372036854775807
ManagerProxyEnd
AllowStateVarsAsJavaClasses=false
AllowScriptedRulesAsJavaClasses=false
HasWaterQualityModule=false
